### ISSUE TITLE
Need German Translate

### ISSUE THREAD

**Issue by SST38** [mahafuz/product-quotation-for-woocommerce#6]
Hey the plugin is exactly what I was looking for, unfortunately I didn't find the option to translate this to German, or even to create the button text individually. Is there an option for this or can you tell me how to do this ?

**Comment by Fantou** [comment]
Hello,


I think you can do this with Loco Plugin. I've succeed to do some translation in French with this

**Comment by mahafuz** [comment]
> 

Hi there, @SST38 @Fantou 👋 
I hope you're having an amazing day. I'm working on the translations please allow me some time to get it done. Hopefully, I'll be able to release the next version in a couple of weeks with some new exciting features and translations.

Thanks best,
Mahafuz

**Comment by Fantou** [comment]
Hello Mahafuz,

Great news! And thanks for the next update!

In this update, will it be possible to modify the form? Or is there already
an option for this?

Thank you!

Le mar. 17 mai 2022 à 09:52, Mahafuzur Rahaman ***@***.***> a
écrit :

**Comment by mahafuz** [comment]
Hi there, @SST38 @Fantou 

As promised, I've released a new version of the plugin and the good news is It comes with the German, Spanish & French translations. 🎉 
I've also added an Elementor widget for **Quotations Cart** I hope you'll find it useful.

Please pardon me If I made any mistakes in the translations that's because I've translated the plugin using **Google Translator**. However, you can always create your own translations by using translator plugins like [Loco Translate](https://wordpress.org/plugins/loco-translate/).

Hey @SST38 I'm still working on the personalize form yet. I'm trying to create a drag & drop form builder for you guys. I hope you'll like it when It'll gets released.

Thanks Best,
Mahafuz

**Comment by Fantou** [comment]
Thank you for your great job @mahafuz !!
